{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "7eba06e2-b6fa-4854-af40-f35c980905a0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from prophet import Prophet\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"COVID-19 Analytics Dashboard\",\n",
    "    layout=\"wide\",\n",
    "    page_icon=\"🌍\"\n",
    ")\n",
    "\n",
    "st.title(\"🌍 COVID-19 Advanced Analytics Dashboard\")\n",
    "st.markdown(\"Interactive visualization & AI forecasting\")\n",
    "\n",
    "# =======================\n",
    "# LOAD DATA\n",
    "# =======================\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    return (\n",
    "        pd.read_csv(\"country_wise_latest.csv\"),\n",
    "        pd.read_csv(\"covid_19_clean_complete.csv\"),\n",
    "        pd.read_csv(\"day_wise.csv\"),\n",
    "        pd.read_csv(\"full_grouped.csv\"),\n",
    "        pd.read_csv(\"usa_country_wise.csv\"),\n",
    "        pd.read_csv(\"worldometer_data.csv\")\n",
    "    )\n",
    "\n",
    "df0, df1, df2, df3, df4, df5 = load_data()\n",
    "st.subheader(\"📈 Global COVID-19 Timeline\")\n",
    "\n",
    "fig = px.line(\n",
    "    df2,\n",
    "    x=\"Date\",\n",
    "    y=[\"Confirmed\",\"Deaths\",\"Recovered\"],\n",
    "    template=\"plotly_dark\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "st.subheader(\"🌍 World COVID-19 Severity Map\")\n",
    "\n",
    "fig = px.choropleth(\n",
    "    df5,\n",
    "    locations=\"Country/Region\",\n",
    "    locationmode=\"country names\",\n",
    "    color=\"TotalCases\",\n",
    "    color_continuous_scale=\"Reds\",\n",
    "    template=\"plotly_dark\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "st.subheader(\"🔮 AI Forecast (Next 60 Days)\")\n",
    "\n",
    "cases = df1.groupby(\"Date\")[\"Confirmed\"].sum().reset_index()\n",
    "cases[\"Date\"] = pd.to_datetime(cases[\"Date\"])\n",
    "\n",
    "df_fb = pd.DataFrame({\n",
    "    \"ds\": cases[\"Date\"],\n",
    "    \"y\": cases[\"Confirmed\"]\n",
    "})\n",
    "\n",
    "model = Prophet()\n",
    "model.fit(df_fb)\n",
    "future = model.make_future_dataframe(periods=60)\n",
    "forecast = model.predict(future)\n",
    "\n",
    "fig = px.line(\n",
    "    forecast,\n",
    "    x=\"ds\",\n",
    "    y=\"yhat\",\n",
    "    template=\"plotly_dark\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
